### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by q66** [void-ppc64/documentation#2]
We need to simplify the installation. That means doing the following:

- [x] add support for live image generation to mklive
- [x] fix GRUB
- [x] working instructions for OpenPOWER hardware
- [x] working instructions for PowerPC Mac hardware
- [x] working instructions for SLOF hardware
- [x] add support for OpenPOWER systems to the installer
- [x] add support for PowerPC Macs to the installer
- [x] add support for SLOF Power systems to the installer
- [x] distribute iso images and rootfs tarballs for all systems
- [x] update the instructions for live images and installer
- [x] test the installer better on native hardware, and fix corner cases (needs testing on native hw, so others should do this)

References:

- GRUB fix: https://github.com/void-linux/void-packages/pull/11851
- Our mklive fork: https://github.com/void-power/void-mklive

**Comment by pullmoll** [comment]
Booting the ppc64 ISO on my G5 succeded. I put the image on an USB stick.
Will try a CD later and will also try the ppc ISO on my G4.

**Comment by q66** [comment]
yeah, booting the live iso should be okay. The tricky part is correctly setting up the bootloader for a real installation, mine is adapted from some tutorial for GRUB/ppc on Gentoo, and should work (works in a VM), but for example Debian installer's logic is a lot more complicated and i'm not entirely sure about the reason for that

**Comment by pullmoll** [comment]
I think the problem boils down to that `hfs` does *officially* support a floppy disk size's filesystem which was 800K back then (80 Tracks with 20 * 512 byte sectors IIRC). You can actually increase the size somewhat like 1,2M or perhaps 1,44M without violating or confusing Mac tools AFAIK.

Since all these sizes are still not sufficient for all of `grub` and its `powerpc-ieee1275` modules to fit in, there is another solution. This creates an initial `grub.img` with embedded config and modules which fits on a 800K `hfs` partition. I found [this page](http://cynic.cc/blog/posts/running_grub2_on_powerpc_macs/#basicsusinggrub2withpowerpc) some time ago which describes how to create such a minimal `grub.img` and includes just the absolutely necessary modules to load the real `grub.cfg` and any further modules from an e.g. `ext2`, `ext4`, or `btrfs` partition where `/boot/grub` can be found.

The description is lengthy yet eventually describes what's required to have a *one time grub on hfs* install where any following updates (kernel, dracut, etc.) do not require touching the `hfs` partition anymore. IIRC I had to strip even more modules from that list to make the `grub.img` fit into 800K.

The embedded config for `grub.img` needs to know the `UUID` or `/dev/disk/by-id/<name>-partX` and path where to find the full blown grub.

I don't know if it makes sense or is required to set up a Mac G5 like this. I haven't had too much luck with `grub` yet and hosed my install several times. Thus for the time being I'm sticking with `yaboot` which always requires manual interaction on kernel updates...

**Comment by q66** [comment]
I don't think we need to do any of that - the current installer seems to be working okay, it just needs a 10MB bootstrap partition instead of 800kB (a 10MB hfs formats fine with `hformat`, it mounts fine, and grub installs its files into it - so that does not seem to be a limitation), it just needs more testing and maybe fixes.

**Comment by pullmoll** [comment]
I think the `pmac-fdisk` is the limiting factor here. Its `b` option creates a 800KB bootpartition without asking for a size.

**Comment by q66** [comment]
Yeah, but you don't need to use `b`. Using `C 2p 10M bootstrap Apple_Bootstrap` works perfectly fine too. (that is what the current `INSTALL.md` suggests, as well as the hint in the installer before it opens `pmac-fdisk`)

**Comment by pullmoll** [comment]
For people who have a standard installation of Mac OS X I think there is usually a 127,5 MB free partition 2 between 1 (partition table) and 3 (Macintosh HD) where the 10 MB should fit. This layout is what I got when I installed OS X on an empty HDD. I don't know if partition 2 is always sufficiently large to put a 10 MB hfs there, though.

**Comment by q66** [comment]
Yeah, I don't know either, as I don't own a Mac; that said, people have been using this, and `yaboot` is deprecated (Debian is ditching it)

**Comment by q66** [comment]
I released a bunch of fresh images again. Most of the issues that have been raised so far should be fixed. Windfarm in initramfs is still not included, so enjoy startup fan noise until rootfs loads, but that's because I don't think it's as simple as force-loading `windfarm_core` (there's specific supplementary windfarm modules for different kinds of G5, which would also need to be included, and then we'd probably need some kind of hook to handle that)

**Comment by pullmoll** [comment]
AFAICT the `windfarm_core` module is all you need to add to the `force drivers` for `dracut` and it'll take care to install the dependent modules. For my PowerMac G5 the list of actually loaded modules with `linux5.1-5.1.6` is this:
```
windfarm_cpufreq_clamp
windfarm_max6690_sensor
windfarm_lm75_sensor
windfarm_smu_sensors
windfarm_smu_controls
windfarm_pm112
windfarm_smu_sat
windfarm_pid
windfarm_core windfarm_cpufreq_clamp,windfarm_smu_controls,windfarm_max6690_sensor,windfarm_smu_sat,windfarm_smu_sensors,windfarm_lm75_sensor,windfarm_pm112
```

BTW booting into Mac OS X using the hold down `Alt` (or Option, or Apple?) key method works just fine albeit slow, because openfirmware searches for a CD and other partitions(?) before allowing you to chose the boot option... anyway, an OS X install survives installing Void if you leave its partition alone and this is *Good News ™*.

**Comment by q66** [comment]
I checked and there is no reason it should pull those in, as if you look at module dependencies, it's the other windfarm modules depending on `windfarm_core` and not the other way around; i.e. including the *others* will pull in windfarm_core, but no the other way around.

Debian's initramfs tools have this kind of hook in them:

```
	case "$MODEL" in
	  RackMac3,1|PowerMac7,2|PowerMac7,3)
	    force_load therm_pm72
	    ;;
	  PowerMac8,1|PowerMac8,2)
	    force_load windfarm_pm81
	    ;;
	  PowerMac9,1)
	    force_load windfarm_pm91
	    ;;
	  PowerMac11,2)
	    force_load windfarm_pm112
	    ;;
	  PowerMac12,1)
	    force_load windfarm_pm121
	    ;;
	  *)
	    # No other machine needs windfarm_* modules on initrd.
	    exit 0
	    ;;
	esac
	manual_add_modules windfarm_core
	manual_add_modules windfarm_cpufreq_clamp
	manual_add_modules windfarm_lm75_sensor
	manual_add_modules windfarm_max6690_sensor
	manual_add_modules windfarm_pid
	manual_add_modules windfarm_smu_controls
	manual_add_modules windfarm_smu_sat
	manual_add_modules windfarm_smu_sensors
```

**Comment by Traace** [comment]
I tried it on a PowerMac G5. 
Installed it via ISO (no network install)
I had to load winfarm_core by hand, even after booted the installation.
(The install guide is well done, thanks :) )

But there are two big issues I ran into:
1. Seems like the newest images have no keys for accessing any repo.
`xbps-query -vL` gives  empty output while `xbps-install -S` gives me a error about there are no certificates and therefore not updating any repo. I run tried to run `update-ca-certificates`, too.

2. The PowerMac G5 shuts down without any kernel panic after 10min of use in void linux. While it works pretty stable with debian and osx leopard.

Any ideas?

**Comment by q66** [comment]
For 1), check if the date in the system is set to something recent

**Comment by pullmoll** [comment]
@Traace take a look into your `dmesg` output to see if a RTC driver is detected and its module loaded.

For `windfarm_core` to be loaded you could try to do this as root
```
echo 'force_drivers+=" windfarm_core "' > /etc/dracut.conf.d/windfarm_core.conf
dracut -f
```
This works for me. I don't really know how the modules depending on windfarm_core are found, i.e. the modules like `windfarm_pmXXX` for the various PowerMac versions, and yet I don't have to be explicit about what modules to load. I believe with `windfarm_core` being loaded the rest is auto detected.

~~For the kernel panic I had that on one G5 machine before it decided to die soon after. Perhaps check your RTC backup battery. In my case it was a `CR2032` type and after replacing it with a fresh one everything works just fine.~~
I misread 2) - It may be that without `windfarm*` modules the CPUs are at maximum all the time and the shutdown is due to a temperature sensor or similar. Note that there's a `windfarm_cpufreq_clamp` module.

**Comment by Traace** [comment]
Thanks for the amazing support.

The repo sync is working now. I forgot that certificates are time-based. The date was set to 1970. That's fixed now.
Guess its time to replace the PRAM battery.
At mine, rtc-generic gets auto loaded. But it can't read the clock.
`rtc_generic: hctosys: unable to read to hardware clock`

After loading `windfarm_cpufreq_clamp` it seems to be stable, too. No shutdown since i loaded it.

Now its time for a bigger challenge. The G5 over here has a FireGL X3 with a reduced bios. Unfortunately the missing part gets injected when booted in osx leopard. This method is uncommon and linux has no automatic solution for this. Because of the frankenstein bios, the system freeze soon after I start a wm like: `xinit pekwm`. This behavior is common for a reduced bios card run under linux.
(I installed some xorg and xserver packages, fonts, ati drivers, and pekwm)

However I think about to inject a whole stock PC FireGL X3 video bios (that should possible with x). It could be a solution. Someone has experience with video bios injections?

**Comment by q66** [comment]
Might be best to just replace the entire GPU... otherwise, there appears to be a flashing tool available for OS X, you could try there

**Comment by Traace** [comment]
Replacing the GPU isn't a suitable option at all. I got 4 powermac's over here, and they all running FireGL X3 cards. Simply because it's the faster gpu available for these machines. Some other users beside me run them, too.

Re-flashing would result in a black-screen because open firmware couldn't find the card anymore.
The only solution I can imagine is to inject the video bios while/after linux booted.

**Comment by q66** [comment]
why can't OF find the card afterwards? It seems several people did it at least

The fastest GPU for AGP is a Radeon HD3850, but I guess OS X can't use it because of lack of drivers

if your powermacs were the PCIe ones, you could just put in just about any GPU...

**Comment by Traace** [comment]
Linux will boot a PC bios card because they have drivers, that's true. But it wouldn't appear in open firmware. The GPU card bios needs to be OF compatible. So people doing that losing open firmware screens and native boot-menu, beside osx compatibility.
In my opinion its not a good solution.

**Comment by q66** [comment]
well, fair enough, is old+unsupported OS X good for anything these days (that you can't replace with running it in virtualization, if you specifically need some application)?

**Comment by Traace** [comment]
Yes, they are still pretty productive. I just compile most newer applications from source because dev's dropped support.

But please I'm seeking help regarding a video bios injection. Not to start a tech discussion.

I'll dig the net for a solution that fits my needs. No worries :+1:

**Comment by q66** [comment]
Okay then

**Comment by q66** [comment]
Got myself this new toy:

![](https://i.imgur.com/FKoo5D6.jpg)
![](https://i.imgur.com/YrEwZLQ.jpg)

I'll look into putting Void on it in near future :)

**Comment by umbertocerrato** [comment]
Wonderful! DC2.3GHz <3

**Comment by classilla** [comment]
Quad or GTFO. ;)

**Comment by q66** [comment]
Well it was basically free, and with DC I don't have to worry about liquid cooling issues ;) Just need to dig up more RAM somewhere... but that should be no problem, DDR2 is what people throw away these days, especially smaller sticks up to 2GB

**Comment by umbertocerrato** [comment]
Oh well I have one of it (Quad) but it needs many fixes!!! LED 2 and 7 powered on, and somebody opened the CPU-heatsink body ...probably without even using an appropriate Allen key!

Anyway, I would like it to look like new... time and space is needed though (LCS and North bridge paste renewal, or removing dust from the power supply, etc.)
PS: ...I was so stupid I broke the clip from the PCIe slot! I would like to desolder and substitute the plastic slot with a new one, they are cheap.

@q66 nothing better than free things xD Anyway yes, you should stay peaceful although the “Quad” should not give problems like the old DP G5s. (I would like to renew it anyway, 14y are a lot!)

PPS:
I was so frustrated about that little clip, I made a blog and a post for it! https://mepypower.blogspot.com/2019/06/apple-powermac-g5-video-card-clip.html

**Comment by q66** [comment]
A locking clip is a pretty standard feature on x16 PCIe slots, never saw too much point in them though, they just make cards hard to remove when the case is cramped :P

**Comment by umbertocerrato** [comment]
Yes :( :(
I’m so sad for it though...

**Comment by Traace** [comment]
OT: Kernel 5.3 will remove NPU DMA code from PowerPC target, used by "out-of-tree" Nvidia drivers.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=192f0f8e9db7efe4ac98d47f5fa4334e43c1204d

So my question is, will it affect G5 users with a Nvidia card?

**Comment by q66** [comment]
No. Nouveau is in-tree, so no reason for it to be affected.

**Comment by q66** [comment]
Proper handling of G5 fan control (`windfarm`) here: https://github.com/void-ppc/void-packages/issues/21

If you have a G5 and run Void on it, please test.
